// Date Formats
const YYYY_MM_DD = "YYYY-MM-DD";

const STR_LOGIN_SUCCESSFULLY_CAP = "LOGIN_SUCCESSFULLY";
const STR_INTERNAL_SERVER_ERROR = "Internal Server Error";
const STR_SOMETHING_WENT_WRONG = "Something went wrong, Please try again later";
const STR_LOGIN_SUCCESSFULLY = "Login successfully";
const STR_EMAIL_OR_PASSWORD_INCORRECT = "Email or Password incorrect";
const STR_EMPLOYEE_DOESNT_EXIST = "Employee doesn't exist";
const STR_ERROR_LOGS_FOR_AUTH_MODULE = "Error Logs for Auth Module ::: ";
const STR_ERROR_LOGS_FOR_BROADCAST_MODULE =
  "Error Logs for Broadcast Module ::: ";
const STR_LOGOUT_SUCCESSFULLY_CAP = "LOGOUT_SUCCESSFULLY";
const STR_PASSWORD_CHANGED_CAP = "PASSWORD_CHANGED";
const STR_OTP_VERIFY_CAP = "OTP_VERIFY";
const STR_MAIL_SENT_CAP = "MAIL_SENT";
const STR_OTP_UPDATED_SUCCESSFULLY = "OTP Updated successfully";
// Department
const STR_DEPARTMENT_ALREADY_EXIST = "Department already exist";
const STR_DEPARTMENT_ADDED_SUCCESSFULLY = "Department added successfully";
const ERROR_WHILE_CREATE = "Error while create a department";
const DEPARTMENT_CREATED = "DEPARTMENT_CREATED";
const STR_DEPARTMENT_LIST_CAP = "DEPARTMENT_LIST";
const DEPARTMENTS_NOT_FOUND = "Department not found";
const STR_DEPARTMENT_FOUND_CAP = "DEPARTMENT_FOUND";
const STR_DEPARTMENT_FOUND_SUCCESSFULLY = "Department found successfully";
const STR_DEPARTMENT_DOES_NOT_EXIST = "Department doesn't exist";
const STR_DEPARTMENT_DELETED_SUCCESSFULLY = "Department deleted successfully";
const STR_DEPARTMENT_DELETED_CAP = "DEPARTMENT_DELETED";
const STR_DEPARTMENT_UPDATED_SUCCESSFULLY = "Department updated successfully";
const STR_USER_DOESNT_EXIST = "User doesn't exist";
const ERROR_WHILE_USER_LOGOUT = "Error while user logout";
const STR_USER_LOGOUT_SUCCESSFULLY = "User logout successfully";
const STR_PASSWORD_UPDATED_SUCCESSFULLY = "Password updated successfully";
const STR_OTP_IS_NOT_VALID = "OTP is not valid";
const STR_OTP_HAS_BEEN_EXPIRED = "OTP has been expired";
const STR_OTP_VERIFIED_SUCCESSFULLY = "OTP verified successfully";
const OTP_SENT = "Otp sent successfully";
const OTP_AFTER_MSG = "A new OTP will be received in the next 15 minutes";
const EMAIL_SENT = "Email will be sent to if exist.";
const OTP_NOT_SENT = "OTP could not be sent to the email";
const OTP_ERROR = "Error in OTP creation";
const STR_POSITION_ADDED_CAP = "POSITION_ADDED";
const STR_POSITION_ADDED_SUCCESSFULLY = "Position added successfully";
const STR_POSITION_FOUND_SUCCESSFULLY = "Position found successfully";
const STR_POSITION_FOUND_CAP = "Position";
const POSITION_ALREADY_EXIST = "Position already exist";
const STR_POSITION_UPDATED_SUCCESSFULLY = "Position updated successfully";
const STR_POSITION_UPDATED_CAP = "POSITION_UPDATED";
const STR_POSITION_DELETED_CAP = "POSITION_DELETED";
const STR_SINGLE_ROLE_CAP = "SINGLE_POSITION";
const STR_POSITION_DOESNT_EXIST = "Position doesn't exist";
const STR_POSITION_DELETED_SUCCESSFULLY = "Position deleted successfully";
const POSITION_DOES_NOT = "Position doesn't exist";
const STR_RIGHT_CREATED_CAP = "RIGHT_CREATED";
const STR_RIGHT_ADDED_SUCCESSFULLY = "Right added successfully";
const ERROR_MSG_RIGHTS = "Something went wrong, try again later";
const STR_RIGHTS_FOUND_CAP = "RIGHTS_FOUND";
const STR_RIGHTS_FOUND_SUCCESSFULLY = "Rights found successfully";
const STR_RIGHTS_ALREADY_EXIST = "Rights already exist";
const STR_RIGHTS_UPDATED_CAP = "RIGHTS_UPDATED";
const STR_RIGHTS_DOESNT_EXIST = "Rights doesn't exist";
const STR_RIGHTS_UPDATED_SUCCESSFULLY = "Rights updated successfully";
const DONT_HAVE_ACCESS = "Don't have access";
const NOT_ACCESS_TO_VIEW = "Don't have access to view";
const NOT_ACCESS_TO_EDIT = "Don't have access to edit";
const STR_REQUIRED_VALIDATION_CAP = "REQUIRED_VALIDATION";
const STR_BROADCAST_CREATED_CAP = "BROADCAST_CREATED";
const STR_BROADCAST_SENT_SUCCESSFULLY = "Broadcast sent successfully";
const STR_BROADCAST_FOUND_CAP = "BROADCAST_FOUND";
const STR_BROADCAST_FOUND_SUCCESSFULLY = "broadcast found successfully";
const STR_BROADCAST_UPDATED_CAP = "BROADCAST_UPDATED";
const STR_BROADCAST_UPDATED_SUCCESSFULLY = "Broadcast update successfully";
const STR_BROADCAST_DELETED_CAP = "BROADCAST_DELETED";
const STR_BROADCAST_DELETED_SUCCESSFULLY = "Broadcast deleted successfully";
const STR_BROADCAST_DOESNT_EXIST = "Broadcast doesn't exist";
const STR_DASHBOARD_DATA_CAP = "DASHBOARD_DATA";
const STR_DASHBOARD_DATA_FOUND_SUCCESSFULLY =
  "Dashboard data found successfully";
const STR_ERROR_LOGS_FOR_DASHBOARD_MODULE =
  "Error Logs for Dashboard Module ::: ";
const STR_USER_CREATED_CAP = "EMPLOYEE_CREATED";
const STR_USER_ADDED_SUCCESSFULLY = "Employee added successfully";
const STR_ALREADY_EXISTS_CAP = "Employee already exist";
const STR_EMPLOYEE_FOUND_CAP = "EMPLOYEE_FOUND";
const STR_EMPLOYEE_FOUND_SUCCESSFULLY = "Employee found successfully";
const STR_EMPLOYEE_UPDATED_CAP = "EMPLOYEE_UPDATED";
const STR_EMPLOYEE_UPDATED_SUCCESSFULLY = "Employee update successfully";
const STR_EMPLOYEE_DELETED_CAP = "EMPLOYEE_DELETED";
const STR_EMPLOYEE_DELETED_SUCCESSFULLY = "Employee deleted successfully";
const STR_TEAM_LEADER_FOUND_CAP = "TEAM_LEADER_FOUND";
const STR_TEAM_LEADER_FOUND_SUCCESSFULLY = "Team leader found successfully";
const STR_YOUR_AADHAR_NUMBER_OR_MOBILE_NUMBER_OR_EMAIL_IS_ALREADY_EXIST =
  "Your aadhar number or mobile number or email is already exist";
const STR_ERROR_LOGS_FOR_EMPLOYEE_MODULE =
  "Error Logs for Employee Module ::: ";
const STR_MALE_CAP = "MALE";
const STR_FEMALE_CAP = "FEMALE";
const STR_OTHER_CAP = "OTHER";
const STR_MARRIED_CAP = "MARRIED";
const STR_UNMARRIED_CAP = "UNMARRIED";
const STR_SPOUSE_CAP = "SPOUSE";
const STR_FATHER_CAP = "FATHER";
const STR_MOTHER_CAP = "MOTHER";
const STR_SISTER_CAP = "SISTER";
const STR_BROTHER_CAP = "BROTHER";
const STR_HOLIDAY_ADDED_CAP = "HOLIDAY_ADDED";
const STR_HOLIDAY_ADDED_SUCCESSFULLY = "Holiday added successfully";
const STR_HOLIDAY_FOUND_CAP = "HOLIDAY_FOUND";
const STR_HOLIDAY_FOUND_SUCCESSFULLY = "Holiday found successfully";
const STR_HOLIDAY_UPDATED_CAP = "HOLIDAY_UPDATED";
const STR_HOLIDAY_UPDATED_SUCCESSFULLY = "Holiday updated successfully";
const STR_HOLIDAY_DELETED_CAP = "HOLIDAY_DELETED";
const STR_HOLIDAY_DELETED_SUCCESSFULLY = "Holiday deleted successfully";
const STR_HOLIDAY_ALREADY_EXIST = "Holiday already exist";
const STR_HOLIDAY_DOESNT_EXIST = "Holiday doesn't exist";
const STR_IMAGE_UPLOADED_CAP = "IMAGE_UPLOADED";
const STR_IMAGE_UPLOADED_SUCCESSFULLY = "Image uploaded successfully";
const STR_IMAGE_DELETED_CAP = "IMAGE_DELETED";
const STR_IMAGE_DELETED_SUCCESSFULLY = "Image deleted successfully";
const STR_LEAVE_APPLIED_CAP = "LEAVE_APPLIED";
const STR_PENDING_LEAVE_FOUND_CAP = "PENDING_LEAVE_FOUND";
const STR_DAY_COUNT_CAP = "DAY_COUNT";
const STR_LEAVES_FOUND_CAP = "LEAVES_FOUND";
const STR_LEAVE_UPDATE_CAP = "LEAVE_UPDATE";
const STR_LEAVE_DELETED_CAP = "LEAVE_DELETED";
const STR_LEAVE_BY_EMPLOYEE_CAP = "LEAVE_BY_EMPLOYEE";
const STR_SINGLE_LEAVE_CAP = "SINGLE_LEAVE";
const STR_TODAY_LEAVE_LIST_CAP = "TODAY_LEAVE_LIST";
const STR_THIS_WEEK_LEAVE_LIST_CAP = "THIS_WEEK_LEAVE_LIST";
const STR_LEAVE_ALREADY_APPLIED_FOR_THESE_DAYS_CHOOSE_OTHER_DAYS =
  "Leave already applied for these days, Choose other days";
const STR_MORNING_CAP = "MORNING";
const STR_EVENING_CAP = "EVENING";
const STR_MAY_BE_LEAVE_DAY_COUNT_NOT_CORRECT =
  "May be leave day count not correct";
const STR_COM_OFF_LEAVE_CAP = "COM_OFF_LEAVE";
const STR_YOU_DONT_HAVE_ENOUGH_COM_OFF_LEAVE =
  "You don't have enough com. off leave";
const STR_UNPAID_LEAVE_CAP = "UNPAID_LEAVE";
const STR_PAID_LEAVE_CAP = "PAID_LEAVE";
const STR_LEAVE_APPLIED_SUCCESSFULLY = "Leave applied successfully";
const STR_YOU_DONT_HAVE_ENOUGH_LEAVE_BALANCE =
  "You have not enough leave balance";
const STR_ERROR_LOGS_FOR_LEAVE_MODULE = "Error Logs for Leave Module ::: ";
const STR_LEAVE_FOUND_CAP = "LEAVE_FOUND";
const STR_LEAVE_FOUND_SUCCESSFULLY = "Leave found successfully";
const STR_LEAVE_DOESNT_EXIST = "Leave doesn't exist";
const STR_PENDING_CAP = "PENDING";
const STR_APPROVED_CAP = "APPROVED";
const STR_REJECTED_CAP = "REJECTED";
const STR_CANCELLED_CAP = "CANCELLED";
const STR_LEAVE_UPDATED_SUCCESSFULLY = "Leave updated successfully";
const STR_LEAVE_DELETED_SUCCESSFULLY = "Leave deleted successfully";
const STR_LEAVE_BALANCE_ADDED_CAP = "LEAVE_BALANCE_ADDED";
const STR_LEAVE_BALANCE_ADDED_SUCCESSFULLY = "Leave balance added successfully";
const STR_LEAVE_BALANCE_FOUND_CAP = "LEAVE_BALANCE_FOUND";
const STR_LEAVE_BALANCE_FOUND_SUCCESSFULLY = "Leave balance found successfully";
const STR_LEAVE_BALANCE_UPDATED_CAP = "LEAVE_BALANCE_UPDATED";
const STR_LEAVE_BALANCE_UPDATED_SUCCESSFULLY =
  "Leave Balance updated successfully";
const STR_COM_OFF_BALANCE_UPDATED_CAP = "COM_OFF_BALANCE_UPDATED";
const STR_COM_OFF_BALANCE_UPDATED_SUCCESSFULLY =
  "Com off Leave Balance updated successfully";
const STR_LEAVE_BALANCE_DOESNT_EXIST = "Leave balance doesn't exist";
const STR_MY_TEAM_FOUND_CAP = "MY_TEAM_FOUND";
const STR_MY_TEAM_LIST_FOUND_SUCCESSFULLY = "My team list found successfully";
const STR_BAD_REQUEST = "BAD REQUEST";
const STR_IMAGE_NOT_FOUND = "Image not found";
const STR_DOCUMENT_NOT_FOUND = "Document not found";
const STR_NO_DATA_FOR_REMOVE = "There is no information available to remove";

module.exports = {
  YYYY_MM_DD,
  STR_MY_TEAM_LIST_FOUND_SUCCESSFULLY,
  STR_MY_TEAM_FOUND_CAP,
  STR_LEAVE_BALANCE_DOESNT_EXIST,
  STR_COM_OFF_BALANCE_UPDATED_SUCCESSFULLY,
  STR_COM_OFF_BALANCE_UPDATED_CAP,
  STR_LEAVE_BALANCE_UPDATED_SUCCESSFULLY,
  STR_LEAVE_BALANCE_UPDATED_CAP,
  STR_LEAVE_BALANCE_FOUND_CAP,
  STR_LEAVE_BALANCE_FOUND_SUCCESSFULLY,
  STR_LEAVE_BALANCE_ADDED_SUCCESSFULLY,
  STR_LEAVE_BALANCE_ADDED_CAP,
  STR_PENDING_CAP,
  STR_LEAVE_DELETED_SUCCESSFULLY,
  STR_LEAVE_UPDATED_SUCCESSFULLY,
  STR_PAID_LEAVE_CAP,
  STR_APPROVED_CAP,
  STR_REJECTED_CAP,
  STR_CANCELLED_CAP,
  STR_LEAVE_DOESNT_EXIST,
  STR_LEAVE_FOUND_CAP,
  STR_LEAVE_FOUND_SUCCESSFULLY,
  STR_ERROR_LOGS_FOR_LEAVE_MODULE,
  STR_YOU_DONT_HAVE_ENOUGH_LEAVE_BALANCE,
  STR_LEAVE_APPLIED_SUCCESSFULLY,
  STR_UNPAID_LEAVE_CAP,
  STR_YOU_DONT_HAVE_ENOUGH_COM_OFF_LEAVE,
  STR_COM_OFF_LEAVE_CAP,
  STR_MAY_BE_LEAVE_DAY_COUNT_NOT_CORRECT,
  STR_MORNING_CAP,
  STR_EVENING_CAP,
  STR_LEAVE_ALREADY_APPLIED_FOR_THESE_DAYS_CHOOSE_OTHER_DAYS,
  STR_THIS_WEEK_LEAVE_LIST_CAP,
  STR_TODAY_LEAVE_LIST_CAP,
  STR_SINGLE_LEAVE_CAP,
  STR_LEAVE_BY_EMPLOYEE_CAP,
  STR_LEAVE_DELETED_CAP,
  STR_LEAVE_UPDATE_CAP,
  STR_LEAVES_FOUND_CAP,
  STR_DAY_COUNT_CAP,
  STR_PENDING_LEAVE_FOUND_CAP,
  STR_LEAVE_APPLIED_CAP,
  STR_IMAGE_DELETED_SUCCESSFULLY,
  STR_IMAGE_DELETED_CAP,
  STR_IMAGE_UPLOADED_SUCCESSFULLY,
  STR_IMAGE_UPLOADED_CAP,
  STR_HOLIDAY_DOESNT_EXIST,
  STR_HOLIDAY_ALREADY_EXIST,
  STR_HOLIDAY_DELETED_CAP,
  STR_HOLIDAY_DELETED_SUCCESSFULLY,
  STR_HOLIDAY_UPDATED_CAP,
  STR_HOLIDAY_UPDATED_SUCCESSFULLY,
  STR_HOLIDAY_FOUND_SUCCESSFULLY,
  STR_HOLIDAY_FOUND_CAP,
  STR_HOLIDAY_ADDED_SUCCESSFULLY,
  STR_HOLIDAY_ADDED_CAP,
  STR_MALE_CAP,
  STR_FEMALE_CAP,
  STR_OTHER_CAP,
  STR_MARRIED_CAP,
  STR_UNMARRIED_CAP,
  STR_SPOUSE_CAP,
  STR_FATHER_CAP,
  STR_MOTHER_CAP,
  STR_SISTER_CAP,
  STR_BROTHER_CAP,
  STR_LOGIN_SUCCESSFULLY_CAP,
  STR_INTERNAL_SERVER_ERROR,
  STR_SOMETHING_WENT_WRONG,
  STR_LOGIN_SUCCESSFULLY,
  STR_EMAIL_OR_PASSWORD_INCORRECT,
  STR_EMPLOYEE_DOESNT_EXIST,
  STR_ERROR_LOGS_FOR_AUTH_MODULE,
  STR_DEPARTMENT_ALREADY_EXIST,
  STR_DEPARTMENT_ADDED_SUCCESSFULLY,
  ERROR_WHILE_CREATE,
  DEPARTMENT_CREATED,
  DEPARTMENTS_NOT_FOUND,
  STR_DEPARTMENT_LIST_CAP,
  STR_DEPARTMENT_DOES_NOT_EXIST,
  STR_DEPARTMENT_FOUND_CAP,
  STR_DEPARTMENT_DELETED_CAP,
  STR_OTP_UPDATED_SUCCESSFULLY,
  STR_DEPARTMENT_UPDATED_SUCCESSFULLY,
  STR_LOGOUT_SUCCESSFULLY_CAP,
  STR_PASSWORD_CHANGED_CAP,
  STR_OTP_VERIFY_CAP,
  STR_MAIL_SENT_CAP,
  STR_USER_DOESNT_EXIST,
  ERROR_WHILE_USER_LOGOUT,
  STR_USER_LOGOUT_SUCCESSFULLY,
  STR_PASSWORD_UPDATED_SUCCESSFULLY,
  STR_OTP_IS_NOT_VALID,
  STR_OTP_HAS_BEEN_EXPIRED,
  STR_OTP_VERIFIED_SUCCESSFULLY,
  OTP_SENT,
  OTP_AFTER_MSG,
  EMAIL_SENT,
  OTP_NOT_SENT,
  OTP_ERROR,
  STR_POSITION_ADDED_CAP,
  STR_POSITION_ADDED_SUCCESSFULLY,
  STR_POSITION_FOUND_SUCCESSFULLY,
  STR_POSITION_FOUND_CAP,
  POSITION_ALREADY_EXIST,
  STR_POSITION_UPDATED_SUCCESSFULLY,
  STR_POSITION_DOESNT_EXIST,
  STR_POSITION_UPDATED_CAP,
  STR_POSITION_DELETED_SUCCESSFULLY,
  POSITION_DOES_NOT,
  STR_POSITION_DELETED_CAP,
  STR_SINGLE_ROLE_CAP,
  STR_RIGHT_CREATED_CAP,
  STR_RIGHT_ADDED_SUCCESSFULLY,
  ERROR_MSG_RIGHTS,
  STR_RIGHTS_FOUND_CAP,
  STR_RIGHTS_FOUND_SUCCESSFULLY,
  STR_RIGHTS_ALREADY_EXIST,
  STR_RIGHTS_UPDATED_CAP,
  STR_RIGHTS_DOESNT_EXIST,
  STR_RIGHTS_UPDATED_SUCCESSFULLY,
  DONT_HAVE_ACCESS,
  NOT_ACCESS_TO_VIEW,
  NOT_ACCESS_TO_EDIT,
  DONT_HAVE_ACCESS,
  STR_REQUIRED_VALIDATION_CAP,
  STR_BROADCAST_CREATED_CAP,
  STR_BROADCAST_SENT_SUCCESSFULLY,
  STR_BROADCAST_FOUND_CAP,
  STR_BROADCAST_FOUND_SUCCESSFULLY,
  STR_BROADCAST_UPDATED_CAP,
  STR_BROADCAST_UPDATED_SUCCESSFULLY,
  STR_BROADCAST_DELETED_CAP,
  STR_BROADCAST_DELETED_SUCCESSFULLY,
  STR_ERROR_LOGS_FOR_BROADCAST_MODULE,
  STR_BROADCAST_DOESNT_EXIST,
  STR_DASHBOARD_DATA_CAP,
  STR_DASHBOARD_DATA_FOUND_SUCCESSFULLY,
  STR_ERROR_LOGS_FOR_DASHBOARD_MODULE,
  STR_DEPARTMENT_FOUND_SUCCESSFULLY,
  STR_DEPARTMENT_DELETED_SUCCESSFULLY,
  STR_USER_CREATED_CAP,
  STR_ALREADY_EXISTS_CAP,
  STR_USER_ADDED_SUCCESSFULLY,
  STR_EMPLOYEE_FOUND_CAP,
  STR_EMPLOYEE_FOUND_SUCCESSFULLY,
  STR_EMPLOYEE_UPDATED_CAP,
  STR_EMPLOYEE_UPDATED_SUCCESSFULLY,
  STR_EMPLOYEE_DELETED_CAP,
  STR_EMPLOYEE_DELETED_SUCCESSFULLY,
  STR_TEAM_LEADER_FOUND_CAP,
  STR_TEAM_LEADER_FOUND_SUCCESSFULLY,
  STR_YOUR_AADHAR_NUMBER_OR_MOBILE_NUMBER_OR_EMAIL_IS_ALREADY_EXIST,
  STR_ERROR_LOGS_FOR_EMPLOYEE_MODULE,
  STR_BAD_REQUEST,
  STR_IMAGE_NOT_FOUND,
  STR_DOCUMENT_NOT_FOUND,
  STR_NO_DATA_FOR_REMOVE,
};
